name: Calendar Summary (Prague 20:00)

on:
  schedule:
    - cron: '0 * * * *'           # běží každou hodinu (spouštíme jen ve 20:00)
  workflow_dispatch:
    inputs:
      mode:
        description: "Run mode"
        required: true
        default: "daily"
        type: choice
        options:
          - daily
          - weekly
          - both

jobs:
  calendar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "recurring-ical-events==2.1.2" "icalendar==5.0.12"

      # výpočet 20:00 Europe/Prague
      - name: Decide if we should run now (Europe/Prague 20:00)
        id: when
        run: |
          python - <<'PY'
          import os
          from datetime import datetime
          import pytz
          tz = pytz.timezone("Europe/Prague")
          now = datetime.now(tz)
          is_20 = now.hour == 20
          is_sun = now.weekday() == 6
          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
              f.write(f"daily={'true' if is_20 else 'false'}\n")
              f.write(f"weekly={'true' if (is_20 and is_sun) else 'false'}\n")
          print("Prague now:", now)
          PY

      - name: Build config.yaml from Secrets/Variables
        run: |
          python .github/workflows/build_config.py
        shell: bash
